site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]

nav:
- Home: 'index.md'
<<<<<<< HEAD
- Quick start:
  - 'Getting started': 'getting_started.md'
  - 'Python API tutorial': 'python_api_tutorial.md'
  - 'Configuring the simulation': 'configuring_the_simulation.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
  - 'F.A.Q.': 'faq.md'
- Building from source:
  - 'How to build on Linux': 'how_to_build_on_linux.md'
  - 'How to build on Windows': 'how_to_build_on_windows.md'
- Advanced topics:
=======
- Getting started:
  - 'Introduction': 'start_introduction.md'
  - 'Quick start installation': 'start_quickstart.md'
- Building CARLA:
  - 'Linux build': 'build_linux.md'
  - 'Windows build': 'build_windows.md'
  - 'Update CARLA': 'build_update.md'
  - 'Build system': 'build_system.md'
  - 'Running in a Docker': 'build_docker.md'
  - 'F.A.Q.': 'build_faq.md'
- First steps:
  - 'Core concepts': 'core_concepts.md'
  - '1st- World and client': 'core_world.md'
  - '2nd- Actors and blueprints': 'core_actors.md'
  - '3rd- Maps and navigation': 'core_map.md'
  - '4th- Sensors and data': 'core_sensors.md'
- Advanced steps:
  - 'OpenDRIVE standalone mode': 'adv_opendrive.md'
  - 'PTV-Vissim co-simulation': 'adv_ptv.md'
  - 'Recorder': 'adv_recorder.md'
  - 'Rendering options': 'adv_rendering_options.md'
  - 'RSS sensor': 'adv_rss.md'
  - 'SUMO co-simulation': 'adv_sumo.md'
  - 'Synchrony and time-step': 'adv_synchrony_timestep.md'
  - 'Traffic Manager': 'adv_traffic_manager.md'
- References:
>>>>>>> 4dc4cb81853670d83ee067ae747c8c851926dacd
  - 'Python API reference': 'python_api.md'
  - 'C++ reference' : 'cpp_reference.md'
  - 'Python Cookbook': 'python_cookbook.md'
  - 'Blueprint Library': 'bp_library.md'
<<<<<<< HEAD
  - 'Running without display and selecting GPUs': 'carla_headless.md'
  - 'Running in a Docker': 'carla_docker.md'
  - "How to create and import a new map": 'how_to_make_a_new_map.md'
  - "How to link Epic's Automotive Materials": 'epic_automotive_materials.md'
  - "Creating standalone asset packages for distribution": 'asset_packages_for_dist.md'
  - "How to record and replay": 'recorder_and_playback.md'
  - "Recorder binary file format": 'recorder_binary_file_format.md'
  - "How to add friction triggers": "how_to_add_friction_triggers.md"
  - "How to control vehicle physics": "how_to_control_vehicle_physics.md"
  - "How to control walker skeletons": "walker_bone_control.md"
=======
  - 'C++ reference' : 'ref_cpp.md'
  - 'Recorder binary file format': 'ref_recorder_binary_file_format.md'
  - "Sensors reference": 'ref_sensors.md'  
- ROS bridge:
  - 'ROS bridge installation': 'ros_installation.md'
  - 'CARLA messages reference': 'ros_msgs.md'
  - 'Launchfiles reference': 'ros_launchs.md'
- Tutorials (general):
  - 'Add friction triggers': "tuto_G_add_friction_triggers.md"
  - 'Control vehicle physics': "tuto_G_control_vehicle_physics.md"
  - 'Control walker skeletons': "tuto_G_control_walker_skeletons.md"
  - 'Retrieve simulation data': "tuto_G_retrieve_data.md"
- Tutorials (assets):
  - 'Add a new map': 'tuto_A_add_map.md'
  - 'Add a new vehicle': 'tuto_A_add_vehicle.md'
  - 'Add new props': 'tuto_A_add_props.md'
  - 'Create standalone packages': 'tuto_A_create_standalone.md'
  - 'Map customization tools': 'tuto_A_map_customization.md'
  - "Material customization": 'tuto_A_material_customization.md'
  - 'Vehicle modelling': 'tuto_A_vehicle_modelling.md'
- Tutorials (developers):
  - 'Contribute with assets': 'tuto_D_contribute_assets.md'
  - 'Create a sensor': 'tuto_D_create_sensor.md'
  - 'Make a release': 'tuto_D_make_release.md'
  - 'Generate pedestrian navigation': 'tuto_D_generate_pedestrian_navigation.md'
>>>>>>> 4dc4cb81853670d83ee067ae747c8c851926dacd
- Contributing:
  - 'Contribution guidelines': 'CONTRIBUTING.md'
  - 'Coding standard': 'coding_standard.md'
  - 'Documentation standard': 'doc_standard.md'
  - 'Code of conduct': 'CODE_OF_CONDUCT.md'
- Development:
  - 'Index': 'dev/index.md'
  - 'Map customization': 'dev/map_customization.md'
  - 'Build system': 'dev/build_system.md'
  - 'How to add a new sensor': 'dev/how_to_add_a_new_sensor.md'
  - "How to upgrade content": 'dev/how_to_upgrade_content.md'
  - "How to make a release": 'dev/how_to_make_a_release.md'
- Art guidelines:
  - 'How to add assets': 'how_to_add_assets.md'
  - 'How to model vehicles': 'how_to_model_vehicles.md'

markdown_extensions:
  - admonition
